from __future__ import annotations

import os
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from subprocess import DEVNULL, CalledProcessError, check_output
from typing import Any


def _write_analytics_config(project_dir: Path) -> None:
    """Write analytics config with Amplitude API key from environment."""
    config_path = project_dir / "src/prefect/_internal/analytics/_config.py"
    api_key = os.environ.get("AMPLITUDE_API_KEY", "YOUR_AMPLITUDE_API_KEY_HERE")

    config_content = textwrap.dedent(f'''\
        # Generated at build time - DO NOT EDIT
        AMPLITUDE_API_KEY = "{api_key}"
    ''')

    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w") as f:
        f.write(config_content)


def write_build_info(
    project_dir: str | Path, template_fields: dict[str, Any], params: dict[str, Any]
) -> None:
    """
    Write the build info to the project directory.
    """
    path = Path(project_dir) / params.get("path", "src/prefect/_version.py")

    try:
        git_hash = (
            check_output(["git", "rev-parse", "HEAD"], stderr=DEVNULL).decode().strip()
        )
    except (CalledProcessError, FileNotFoundError):
        git_hash = "unknown"

    build_dt_str = template_fields.get(
        "build_date", datetime.now(timezone.utc).isoformat()
    )
    version = template_fields.get("version", "unknown")
    dirty = "dirty" in version

    build_info = textwrap.dedent(
        f"""\
            # Generated by versioningit
            __version__ = "{version}"
            __build_date__ = "{build_dt_str}"
            __git_commit__ = "{git_hash}"
            __dirty__ = {dirty}
            """
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(build_info)

    _write_analytics_config(Path(project_dir))


def get_build_hook():
    from hatchling.builders.hooks.plugin.interface import BuildHookInterface

    class BuildInfoBuildHook(BuildHookInterface):
        def initialize(self, version: str, build_data: dict[str, Any]) -> None:
            write_build_info(
                self.root,
                {"version": self.metadata.version},
                {
                    "path": self.config.get(
                        "build-info-path", "src/prefect/_build_info.py"
                    )
                },
            )

    return BuildInfoBuildHook
